version: '3'

volumes:
  node_modules:
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.wagtail
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # you can use the tail -F anything command to start an empty container
    command: tail -F anything 
    #command: python manage.py runserver 0.0.0.0:${DOCKER_DJANGO_PORT:-8000}
    volumes:
      - .:/code
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - node_modules:/code/node_modules/
    ports:
      - "${DOCKER_DJANGO_PORT:-8000}:${DOCKER_DJANGO_PORT:-8000}"
      - 5432
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@${POSTGRES_HOST:-host.docker.internal}:5432/$POSTGRES_DATABASE
  # Optional redis container
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   expose:
  #     - 6379
  # Optional celery container
  # celery:
  #   restart: always
  #   build:
  #     context: .
  #   command: celery -A <project_name> worker -l info
  #   volumes:
  #     - .:/code
  #   environment:
  #     DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@${POSTGRES_HOST:-host.docker.internal}:5432/$POSTGRES_DATABASE
  #   depends_on:
  #     - redis
  #     - web